version: "3"

networks: 
  elk:
    driver: bridge

volumes:
  elasticsearch: {}

services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    restart: on-failure
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks: 
      - elk
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    restart: on-failure
    ports:
     - 5601:5601
    networks: 
      - elk
    depends_on:
      - elasticsearch
  
  apm:
    image: docker.elastic.co/apm/apm-server:7.2.0
    restart: on-failure
    ports:
     - 8200:8200
    volumes:
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml
    networks: 
      - elk
    environment:
      - strict.perms=false
    depends_on:
      - elasticsearch